1.
SELECT L_PARTKEY, L_QUANTITY
FROM LINEITEM
WHERE L_SHIPDATA= '1992-04-01';

2.
SELECT L_SHIPMODE, sum(L_QUANTITY)
FROM LINEITEM
WHERE L_SHIPDATE < DATE ('1992-10-01')
GROUP BY L_SHIPMODE
ORDER BY sum(L_QUANTITY) desc;

3.
SELECT COUNT(*)
FROM LINEITEM
WHERE L_COMMENT LIKE '%carefully%';

4.
SELECT sum(L_QUANTITY)
FROM LINEITEM, ORDERS
WHERE L_SHIPMODE= 'RAIL'
and O_ORDERPRIORITY= '1-URGENT'
and L_ORDERKEY=O_ORDERKEY;

5.
SELECT S_NAME, N_NAME, R_NAME, P_BRAND
FROM SUPPLIER, NATION, PARTSUPP, REGION, PART
where PS_PARTKEY= 99
and PS_SUPPKEY=S_SUPPKEY
and S_NATIONKEY=N_NATIONKEY
and P_PARTKEY= PS_PARTKEY
and R_REGIONKEY=N_REGIONKEY;

6.
SELECT count(DISTINCT O_CUSTKEY)
FROM LINEITEM, PART, ORDERS
WHERE P_TYPE LIKE '%STEEL'
and L_PARTKEY=P_PARTKEY
and O_ORDERKEY=L_ORDERKEY;

7.
SELECT P_PARTKEY, P_NAME, P_BRAND, TEMP.TOTAL_QUANTITY
FROM (
	SELECT L_PARTKEY, SUM(L_QUANTITY) AS TOTAL_QUANTITY
	FROM LINEITEM, PART
	WHERE P_PARTKEY=L_PARTKEY
	and L_SHIPDATE >= DATE ('1996-01-01')
	and L_SHIPDATE < DATE ('1997-01-01')
	GROUP BY L_PARTKEY
      )AS TEMP , PART
WHERE TEMP.L_PARTKEY= PART.P_PARTKEY
ORDER BY TOTAL_QUANTITY
LIMIT 10;

8.
SELECT C_CUSTKEY, C_NAME, C_ADDRESS, C_PHONE, TEMP.TOTAL_ORDER
FROM (
	SELECT O_CUSTKEY, COUNT(*) AS TOTAL_ORDER
	FROM CUSTOMER, ORDERS
	WHERE C_CUSTKEY= O_CUSTKEY
	AND O_ORDERDATE>= DATE('1998-01-01')
	AND O_ORDERDATE< DATE('1999-01-01')
	GROUP BY O_CUSTKEY
     ) AS TEMP, CUSTOMER
WHERE TEMP.O_CUSTKEY= CUSTOMER.C_CUSTKEY
AND TOTAL_ORDER>= 10
ORDER BY TOTAL_ORDER desc;

9.
SELECT MAX(L_EXTENDEDPRICE)
FROM ( 
	SELECT *
	FROM LINEITEM, ORDERS
	WHERE L_ORDERKEY = O_ORDERKEY
	and L_DISCOUNT= 0.10
	and O_ORDERDATE >= DATE('1998-01-01')
	and O_ORDERDATE < DATE('1999-01-01')
) AS TEMP;

10.
SELECT L_SHIPMODE, sum(L_QUANTITY)
FROM LINEITEM, ORDERS
WHERE L_ORDERKEY = O_ORDERKEY
and O_ORDERDATE >= DATE('1995-05-01')
and O_ORDERDATE < DATE('1995-06-01')
and L_SHIPMODE not in ( 'AIR','SHIP')
GROUP BY L_SHIPMODE;